name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Get full Python version
      shell: bash
      run: echo ::set-output name=version::$(python -c "import sys; print('-'.join(str(v) for v in sys.version_info))")
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.1.10
    - name: Bootstrap poetry
      shell: bash
      run: |
        curl -sL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py \
          | python - -y --git https://github.com/python-poetry/poetry.git
    - name: Update PATH
      shell: bash
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH
    - name: Configure poetry
      shell: bash
      run: poetry config virtualenvs.in-project true
    - name: Install dependencies
      shell: bash
      run: poetry install
    - name: Run pytest
      shell: bash
      run: poetry run pytest -s tests/ --quiet